server:
  port: 8080

spring:
  application:
    name: compta-pro

  servlet:
    multipart:
      enabled: true
      max-file-size: 300MB
      max-request-size: 300MB

  datasource:
    url: jdbc:postgresql://${DB_HOST:72.60.188.97}:${DB_PORT:5432}/${DB_NAME:compta}
    username: ${DB_USERNAME:formation}
    password: ${DB_PASSWORD:formation}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

logging:
  level:
    com.comptapro: DEBUG
    org.hibernate.SQL: DEBUG
